# Configure Riak connections for the Ripple library.
development:
  http_port: 10018
  pb_port: 10017
  host: 127.0.0.1
  source: /home/ghost/Projects/riak-db/rel/riak/bin

test:
  http_port: 9000
  pb_port: 9002
  host: 127.0.0.1
  source: /home/ghost/Projects/riak-db/rel/riak/bin
  js_source_dir: <%= Rails.root + "app/mapreduce" %>

production:
  http_port: 10018
  pb_port: 8087
  host: 127.0.0.1
