--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
http_port: 8098
pb_port: 8087
host: 127.0.0.1
source: /home/ghost/Projects/riak-db/rel/riak/bin
min_port: 9000
root: !ruby/object:Pathname
  path: /home/ghost/Projects/riak/db/development/1
cookie: '97069_891434'
env: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  riak_core: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    ring_creation_size: 64
    ring_state_dir: /home/ghost/Projects/riak/db/development/1/ring
    slide_private_dir: /home/ghost/Projects/riak/db/development/1/data/slide-data
    platform_bin_dir: /home/ghost/Projects/riak/db/development/1/bin
    platform_etc_dir: /home/ghost/Projects/riak/db/development/1/etc
    platform_log_dir: /home/ghost/Projects/riak/db/development/1/log
    platform_data_dir: /home/ghost/Projects/riak/db/development/1/data
    http:
    - !ruby/array:Riak::Node::Tuple
      - 127.0.0.1
      - 9000
    handoff_port: 9002
  riak_kv: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    storage_backend: :riak_kv_bitcask_backend
    map_js_vm_count: 8
    reduce_js_vm_count: 6
    hook_js_vm_count: 2
    mapper_batch_size: 5
    js_max_vm_mem: 8
    js_thread_stack: 16
    riak_kv_stat: true
    legacy_stats: true
    vnode_vclocks: true
    http_url_encoding: :on
    legacy_keylisting: false
    mapred_system: :pipe
    mapred_2i_pipe: true
    listkeys_backpressure: true
    add_paths: []
    pb_ip: 127.0.0.1
    pb_port: 9001
  riak_search: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: true
  luwak: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: true
  merge_index: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    buffer_rollover_size: 1048576
    max_compact_segments: 20
    data_root: /home/ghost/Projects/riak/db/development/1/data/merge_index
  eleveldb: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    data_root: /home/ghost/Projects/riak/db/development/1/data/leveldb
  bitcask: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    data_root: /home/ghost/Projects/riak/db/development/1/data/bitcask
  lager: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    crash_log_size: 10485760
    crash_log_msg_size: 65536
    crash_log_date: $D0
    crash_log_count: 5
    error_logger_redirect: true
    handlers: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      lager_console_backend: :info
      lager_file_backend:
      - !ruby/array:Riak::Node::Tuple
        - /home/ghost/Projects/riak/db/development/1/log/error.log
        - :error
      - !ruby/array:Riak::Node::Tuple
        - /home/ghost/Projects/riak/db/development/1/log/console.log
        - :info
    crash_log: /home/ghost/Projects/riak/db/development/1/log/crash.log
  riak_sysmon: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    process_limit: 30
    port_limit: 30
    gc_ms_limit: 100
    heap_word_limit: 40111000
    busy_port: true
    busy_dist_port: true
  sasl: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sasl_error_logger: false
  riak_control: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: false
    auth: :userlist
    userlist: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      user: pass
    admin: true
vm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  +K: true
  +A: 64
  -smp: enable
  +W: w
  -env ERL_MAX_PORTS: 4096
  -env ERL_FULLSWEEP_AFTER: 0
  -env ERL_CRASH_DUMP: /home/ghost/Projects/riak/db/development/1/log/erl_crash.dump
  -name: riak101206@127.0.0.1
  -setcookie: '97069_891434'
